name: Build App

on:
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      comment:
        description: Comment on triggering this workflow
        required: false
env:
  REGISTRY_REPO: seventv/app
  REGISTRTY_IMAGE_NAME: seventv/app:${{ github.sha }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image with Server-Side Rendering & Push to Packages
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/seventv/app:${{ github.sha }}
            ghcr.io/seventv/app:latest

  deploy:
    name: Deploy (Production)
    runs-on: self-hosted
    needs: 
      - build

    steps:
      - name: Deploy Production Server
        uses: fifsky/ssh-action@master
        with:
          command: docker pull ghcr.io/seventv/autodeploy:latest && docker run --net=host -v /opt/autodeploy/config.yaml:/app/config.yaml -v /opt/autodeploy/private.key:/app/private.key ghcr.io/seventv/autodeploy:latest --service webapp --tag ${{ github.sha }}
          host: ${{ secrets.DEPLOY_HOST }}
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
